INSERT INTO `requerimento` 
(`id_requerimento`, `titulo`, `tipo`, `situacao`, `data`, `descricao`, `cep`, `cidade`, `bairro`, `rua`, `imagem`)
VALUES
(1, 'Melhoria na acessibilidade', 'Sugestão', 'Em andamento', '10/08/2023', 'Sugiro que sejam realizadas melhorias na acessibilidade do local, como rampas e sinalizações adequadas.', '12.345-678', 'Cidade Acessível', 'Centro', 'Rua da Inclusão', 'imagem1.jpg'),
(2, 'Irregularidade de acesso', 'Denúncia', 'Em vistoria', '15/07/2023', 'Denuncio a falta de rampa de acesso ao prédio, impossibilitando a entrada de pessoas com mobilidade reduzida.', '98.765-432', 'Cidade Acessível', 'Bairro Inclusivo', 'Avenida da Igualdade', 'imagem2.jpg'),
(3, 'Falta de recursos táteis', 'Sugestão', 'Recusado', '05/06/2023', 'Sugiro a instalação de sinalizações táteis no chão para auxiliar pessoas com deficiência visual a se locomoverem com mais segurança.', '11.223-344', 'Cidade Acessível', 'Bairro da Diversidade', 'Travessa da Acessibilidade', 'imagem3.jpg'),
(4, 'Acesso dificultado por degraus', 'Denúncia', 'Em vistoria', '22/08/2023', 'Denuncio a presença de degraus na entrada do prédio, tornando difícil o acesso de cadeirantes.', '55.555-555', 'Cidade Acessível', 'Bairro da Inclusão', 'Rua das Barreiras', 'imagem4.jpg'),
(5, 'Sinalização inadequada', 'Sugestão', 'Em andamento', '18/07/2023', 'Sugiro a implementação de sinalizações claras e visíveis para indicar as rotas acessíveis no estabelecimento.', '88.888-888', 'Cidade Inclusiva', 'Bairro Acessível', 'Avenida da Orientação', 'imagem5.jpg'),
(6, 'Falta de elevador', 'Denúncia', 'Em vistoria', '03/08/2023', 'Denuncio a ausência de um elevador no prédio de vários andares, o que impossibilita a locomoção de pessoas com mobilidade reduzida.', '77.777-777', 'Cidade da Acessibilidade', 'Centro Inclusivo', 'Rua da Mobilidade', 'imagem6.jpg'),
(7, 'Ausência de vagas reservadas', 'Sugestão', 'Recusado', '12/06/2023', 'Sugiro a criação de vagas de estacionamento reservadas para veículos que transportem pessoas com deficiência, próximas à entrada do estabelecimento.', '66.666-666', 'Cidade Acessível', 'Bairro da Igualdade', 'Praça da Acessibilidade', 'imagem7.jpg'),
(8, 'Falta de piso tátil', 'Denúncia', 'Em vistoria', '09/08/2023', 'Denuncio a ausência de piso tátil em calçadas e áreas públicas, prejudicando a locomoção de pessoas com deficiência visual.', '44.444-444', 'Cidade Inclusiva', 'Bairro Acessível', 'Rua do Tato', 'imagem8.jpg'),
(9, 'Escadas sem corrimão', 'Denúncia', 'Em vistoria', '27/07/2023', 'Denuncio a falta de corrimão nas escadas do prédio, o que representa um risco para pessoas com dificuldade de equilíbrio.', '33.333-333', 'Cidade da Acessibilidade', 'Centro Inclusivo', 'Avenida da Segurança', 'imagem9.jpg'),
(10, 'Iluminação insuficiente', 'Sugestão', 'Em andamento', '14/06/2023', 'Sugiro a melhoria na iluminação das áreas externas, visando proporcionar maior segurança aos pedestres, especialmente à noite.', '22.222-222', 'Cidade Acessível', 'Bairro da Segurança', 'Travessa da Visibilidade', 'imagem10.jpg'),
(11, 'Falta de rampa na calçada', 'Denúncia', 'Em vistoria', '05/08/2023', 'Denuncio a falta de rampa de acesso na calçada, dificultando a passagem de cadeirantes e carrinhos de bebê.', '99.999-999', 'Cidade da Acessibilidade', 'Bairro Inclusivo', 'Rua da Inclusão', 'imagem11.jpg'),
(12, 'Banheiros sem adaptações', 'Denúncia', 'Em vistoria', '17/07/2023', 'Denuncio a ausência de banheiros adaptados para pessoas com deficiência, o que limita sua participação em eventos públicos.', '88.877-777', 'Cidade Acessível', 'Bairro da Igualdade', 'Praça da Equidade', 'imagem12.jpg'),
(13, 'Falta de comunicação acessível', 'Sugestão', 'Em andamento', '29/06/2023', 'Sugiro que informações importantes sejam disponibilizadas em formatos acessíveis, como Libras e Braille, para atender a diversos públicos.', '77.766-666', 'Cidade Inclusiva', 'Bairro da Diversidade', 'Avenida da Comunicação', 'imagem13.jpg'),
(14, 'Acessos estreitos', 'Sugestão', 'Recusado', '08/06/2023', 'Sugiro a ampliação dos acessos para o prédio, a fim de permitir a passagem de cadeirantes e carrinhos de bebê com facilidade.', '55.554-444', 'Cidade da Acessibilidade', 'Bairro Acessível', 'Rua da Amplitude', 'imagem14.jpg'),
(15, 'Falta de audiodescrição', 'Sugestão', 'Em andamento', '25/07/2023', 'Sugiro que eventos e apresentações visuais contem com serviço de audiodescrição para torná-los acessíveis a pessoas com deficiência visual.', '33.332-222', 'Cidade Acessível', 'Centro da Inclusão', 'Praça da Audiodescrição', 'imagem15.jpg'),
(16, 'Ausência de assentos acessíveis', 'Sugestão', 'Recusado', '02/06/2023', 'Sugiro que o local disponibilize assentos adaptados para pessoas com mobilidade reduzida em áreas de espera e lazer.', '11.112-222', 'Cidade da Acessibilidade', 'Bairro Inclusivo', 'Avenida da Comodidade', 'imagem16.jpg'),
(17, 'Falta de comunicação em Libras', 'Sugestão', 'Em andamento', '19/08/2023', 'Sugiro que funcionários recebam treinamento em Libras para facilitar a comunicação com pessoas surdas.', '22.221-111', 'Cidade Acessível', 'Bairro da Diversidade', 'Rua da Linguagem', 'imagem17.jpg'),
(18, 'Degraus no transporte público', 'Denúncia', 'Em vistoria', '10/08/2023', 'Denuncio a presença de degraus nos ônibus, dificultando o acesso de cadeirantes e pessoas com carrinhos de bebê.', '99.988-877', 'Cidade da Acessibilidade', 'Bairro Inclusivo', 'Avenida do Transporte', 'imagem18.jpg'),
(19, 'Falta de orientação tátil', 'Sugestão', 'Em andamento', '31/07/2023', 'Sugiro a instalação de trilhas táteis para orientar pessoas com deficiência visual em espaços públicos.', '44.443-332', 'Cidade Acessível', 'Bairro Acessível', 'Praça da Orientação', 'imagem19.jpg'),
(20, 'Acessibilidade nos eventos', 'Sugestão', 'Recusado', '15/06/2023', 'Sugiro que eventos realizados na cidade ofereçam estrutura acessível, como intérpretes de Libras e espaços reservados para cadeirantes.', '22.211-000', 'Cidade Inclusiva', 'Bairro da Diversidade', 'Rua da Participação', 'imagem20.jpg');

